config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
	mount Sidekiq::Web => '/sidekiq'

	root to: 'home#index'
  resources :users
	resources :tickets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :ticket

  # Validations
  validates :message, presence: true
  validates :sent_at, presence: true
  validates :notification_type, presence: true

  # Enum for notification types
  enum notification_type: { email: 0 }
end

app/models/status.rb
class Status < ApplicationRecord
  # Associations
  has_many :tickets

  # Validations
	validates :name, presence: true, uniqueness: true

	# Enum for status name
	enum name: { pending: 0, in_progress: 1, completed: 2, on_hold: 3, resolved: 4, over_due: 5 }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  # Associations
	has_many :notifications, dependent: :destroy
	belongs_to :assigned_user, class_name: 'User', foreign_key: 'assigned_user_id', required: true
  belongs_to :status

  # Validations
  validates :title, presence: true
  validates :description, presence: true
  validates :assigned_user_id, presence: true
	validates :status_id, presence: true
	validates :due_date, presence: true
	validates :progress, numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100,
    only_integer: true,
    message: "must be an integer between 0 and 100" 
  }

	validate :due_date_not_in_the_past

	# Callbacks
	after_save :schedule_due_date_reminder, if: -> { saved_change_to_due_date? }

	def schedule_due_date_reminder
    cancel_existing_job if reminder_job_id.present?
		unless assigned_user&.send_due_date_reminder
			self.reminder_job_id = nil
			self.save
			return
		end

    reminder_time = calculate_reminder_time
    # Schedule the new reminder job
    self.reminder_job_id = SendDueDateReminderJob.perform_at(reminder_time, self.id)
		self.save
  end

	private

	def due_date_not_in_the_past
    errors.add(:due_date, "can't be in the past") if due_date.present? && due_date < Date.today
  end

	def cancel_existing_job
    Sidekiq::ScheduledSet.new.find_job(reminder_job_id)&.delete if reminder_job_id.present?
  end

	def calculate_reminder_time
		user_time_zone = TZInfo::Timezone.get(assigned_user.time_zone) rescue TZInfo::Timezone.get('Europe/Vienna')
		# Calculate reminder time in user's time zone
		reminder_time_in_user_tz = due_date.to_time - assigned_user.due_date_reminder_interval.days
		reminder_time_in_user_tz = reminder_time_in_user_tz.change(hour: assigned_user.due_date_reminder_time.hour, 
																															 min: assigned_user.due_date_reminder_time.min)
		# Convert reminder time back to UTC for scheduling
		user_time_zone.local_to_utc(reminder_time_in_user_tz)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Associations
  has_many :notifications, dependent: :destroy
  has_many :tickets, dependent: :destroy, foreign_key: :assigned_user_id

  # Validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "is not a valid email" }
	validates :time_zone, presence: true
  validate :valid_time_zone

	# Callbacks
	after_save :reschedule_due_date_reminders, if: -> { due_date_reminder_settings_changed? }

	private

  def valid_time_zone
    begin
      TZInfo::Timezone.get(time_zone)
    rescue TZInfo::InvalidTimezoneIdentifier
      errors.add(:time_zone, "is not a valid time zone")
    end
  end

	def due_date_reminder_settings_changed?
		saved_change_to_send_due_date_reminder? ||
    saved_change_to_due_date_reminder_interval? ||
    saved_change_to_due_date_reminder_time? ||
		saved_change_to_time_zone?
  end

	def reschedule_due_date_reminders
		tickets.each(&:schedule_due_date_reminder)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy]

  # GET /tickets
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @users = User.all
    @statuses = Status.all
  end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully created.'
    else
      render :new
    end
  end

  # GET /tickets/:id
  def show
  end

  # GET /tickets/:id/edit
  def edit
    @users = User.all
    @statuses = Status.all
  end

  # PATCH/PUT /tickets/:id
  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Ticket was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tickets/:id
  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:title, :description, :due_date, :assigned_user_id, :status_id, :progress)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/:id
  def show
		@tickets = @user.tickets
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # GET /users/:id/edit
  def edit
  end

  # PATCH/PUT /users/:id
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/:id
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Set user based on params
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through
  def user_params
    params.require(:user).permit(:name, :email, :send_due_date_reminder, :due_date_reminder_interval, :due_date_reminder_time, :time_zone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to the Dashboard</h1>

<div>
  <%= link_to 'View Users', users_path, class: 'btn btn-primary' %>
</div>

<div>
  <%= link_to 'View Tickets', tickets_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketReminderApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= form_with(model: @ticket, local: true) do |form| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% @ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_field :due_date %>
  </div>

  <div class="field">
    <%= form.label :progress %>
    <%= form.number_field :progress %>
  </div>

  <div class="field">
    <%= form.label :assigned_user_id %>
		<%= form.collection_select :assigned_user_id, @users.presence || [], :id, :name, prompt: 'Select User' %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.collection_select :status_id, @statuses.presence || [], :id, :name, prompt: 'Select Status' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<table>
	<% if @tickets.any? %>
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Assigned User</th>
				<th>Status</th>
				<th>Due Date</th>
				<th>Progress</th>
				<th colspan="3"></th>
			</tr>
		</thead>
	<% end %>


  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.assigned_user&.name %></td>
        <td><%= ticket.status.name.capitalize %></td>
        <td><%= ticket.due_date %></td>
				<td><%= ticket.progress %></td>
        <td><%= link_to 'Show', ticket_path(ticket) %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= form_with model: ticket, method: :delete, data: { confirm: 'Are you sure?' } do |form| %>
  				<%= form.submit 'Destroy' %></td>
<% end %>
				</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= form_with(model: @ticket, local: true) do |form| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% @ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_field :due_date %>
  </div>

  <div class="field">
    <%= form.label :assigned_user_id %>
    <%= form.collection_select :assigned_user_id, @users.presence || [], :id, :name, prompt: 'Select User' %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.collection_select :status_id, @statuses.presence || [], :id, :name, prompt: 'Select Status' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<h1>Ticket Details</h1>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Assigned User:</strong>
  <%= @ticket.assigned_user.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status.name.capitalize %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= @ticket.due_date %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @ticket.progress %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->

<h1>Edit User</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :send_due_date_reminder %>
    <%= form.check_box :send_due_date_reminder %>
  </div>

  <div>
    <%= form.label :due_date_reminder_interval %>
    <%= form.number_field :due_date_reminder_interval %>
  </div>

  <div>
    <%= form.label :due_date_reminder_time %>
    <%= form.time_select :due_date_reminder_time %>
  </div>

  <div>
    <%= form.label :time_zone %>
    <%= form.text_field :time_zone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Users', users_path %>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->

<h1>Users</h1>
<%= link_to 'New User', new_user_path %>

<table>
	<% if @users.any? %>
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Actions</th>
			</tr>
		</thead>
	<% end %>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Show', user_path(user) %> |
          <%= link_to 'Edit', edit_user_path(user) %> |
          <%= form_with model: user, method: :delete, data: { confirm: 'Are you sure?' } do |form| %>
						<%= form.submit 'Destroy' %>
					<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->

<h1>New User</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :send_due_date_reminder %>
    <%= form.check_box :send_due_date_reminder %>
  </div>

  <div>
    <%= form.label :due_date_reminder_interval %>
    <%= form.number_field :due_date_reminder_interval %>
  </div>

  <div>
    <%= form.label :due_date_reminder_time %>
    <%= form.time_select :due_date_reminder_time %>
  </div>

  <div>
    <%= form.label :time_zone %>
    <%= form.text_field :time_zone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Users', users_path %>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<h1>User: <%= @user.name %></h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Due Date Reminder:</strong>
  <%= @user.send_due_date_reminder ? 'Enabled' : 'Disabled' %>
</p>

<p>
  <strong>Reminder Interval:</strong>
  <%= @user.due_date_reminder_interval %>
</p>

<p>
  <strong>Reminder Time:</strong> 
  <%= @user.due_date_reminder_time.strftime("%H:%M") %>
</p>

<p>
  <strong>Time Zone:</strong>
  <%= @user.time_zone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back to Users', users_path %>
<hr>

<h2>Assigned Tickets</h2>

<% if @tickets.any? %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Due Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.title %></td>
          <td><%= ticket.description %></td>
          <td><%= ticket.status.name %></td>
          <td><%= ticket.due_date %></td>
          <td>
            <%= link_to 'Show', ticket_path(ticket) %> |
            <%= link_to 'Edit', edit_ticket_path(ticket) %> |
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No tickets assigned.</p>
<% end %>